[colors]
draw_bold_text_with_bright_colors = true

[cursor]
thickness = 0.15
# vi_mode_style = "None"

[cursor.style]
blinking = "Off"
# shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
# family = "IosevkaTerm Nerd Font"
family = "MesloLGS Nerd Font"
# family = "FiraCode Nerd Font"
style = "Regular"

# [font.offset]
# x = 0
# y = -3

[keyboard]
bindings = [
	{ key = "Slash", mods = "Control", chars = "\u001f" },
	{ key = "Back", mods = "Control", chars = "\u0017" },
]

# [[keyboard.bindings]]
# chars = "\u0017"
# key = "Back"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "ToggleFullscreen"
# key = "F11"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
option_as_alt = "Both"
#opacity = 0.95

[window.padding]
x = 0
y = 0

